fn:
   vars:
    ansible_host: "{{ host }}"
    ansible_user: "{{ login }}"
   children:
    webservers:
      hosts:
        fnherstal.adminweb:
        fnherstal.vitrineweb:
    db_servers:
      hosts:
        fnherstal.bdd:

