---
- name: Install necessary packages and configure MariaDB
  hosts: bdd1
  become: yes

  vars:
    mariadb_root_password: "fn12hs3."
    mariadb_database: "fn_bdd"
    mariadb_user: "fn"
    mariadb_password: "fn"

  tasks:
    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - sudo
        - python3-pymysql
        - mariadb-server
        - python3-pip
        - python3-dev
        - libmysqlclient-dev

    - name: Ensure MariaDB service is running and enabled
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Set root password for MariaDB
      mysql_user:
        name: root
        password: "{{ mariadb_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
      ignore_errors: true

    - name: Create database
      mysql_db:
        name: "{{ mariadb_database }}"
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create database user
      mysql_user:
        name: "{{ mariadb_user }}"
        password: "{{ mariadb_password }}"
        priv: "{{ mariadb_database }}.*:ALL"
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present

    - name: Install mysqlclient module using pip
      pip:
        name: mysqlclient
        state: present
        executable: pip3

