- hosts: fn
  become: true
  tasks:
    - name: Create users
      ansible.builtin.user:
        name: "{{ item.login }}"
        shell: "{{ default_shell }}"
        groups: "{{ item.groups }}"
        append: yes
      loop: "{{ myusers }}"

    - name: Set users authorized key
      #removing all the authorized keys already set
      ansible.posix.authorized_key:
        user: "{{ item.login }}"
        key: "{{ item.pubkey }}"
        state: present
        exclusive: true
      loop: "{{ myusers }}"
