- name: Update apt and install necessary packages
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    - p7zip-full
    - git

- name: Enable and start Apache
  service:
    name: apache2
    state: started
    enabled: yes

- name: Clone the website repository
  git:
    repo: "{{ repo_url }}"
    dest: "/var/www/html/{{ site_name }}"
    version: master

- name: Remove default Apache configuration
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent

- name: Deploy custom Apache configuration
  template:
    src: "{{ apache_conf_template }}"
    dest: "/etc/apache2/sites-available/{{ site_name }}.conf"

- name: Enable website configuration
  file:
    src: "/etc/apache2/sites-available/{{ site_name }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ site_name }}.conf"
    state: link

- name: Restart Apache to apply changes
  service:
    name: apache2
    state: restarted
